name: CI

on: workflow_dispatch
env:
  CACHE_IMAGE: hsahbus/demo
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Log in to docker hub
      run: docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }}
    - name: Build from dockerfile
      run: |
          docker build \
            --cache-from $CACHE_IMAGE:latest \
            --tag $CACHE_IMAGE:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            "."
    - name: Push to docker hub
      run: docker push $CACHE_IMAGE:v1.0

   
